# Generated by Django 2.1.1 on 2018-10-11 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('street_number', models.PositiveIntegerField()),
                ('flat_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.TextField()),
                ('email_type', models.IntegerField(choices=[(0, 'Home'), (1, 'Work'), (2, 'Other')])),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.PositiveIntegerField()),
                ('type_number', models.IntegerField(choices=[(0, 'Mobile'), (1, 'Work'), (2, 'Home'), (3, 'Work Fax'), (4, 'Home Fax'), (5, 'Other')])),
                ('persons', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contact_box.Person')),
            ],
        ),
        migrations.AddField(
            model_name='groups',
            name='persons',
            field=models.ManyToManyField(related_name='group', to='contact_box.Person'),
        ),
        migrations.AddField(
            model_name='email',
            name='persons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contact_box.Person'),
        ),
        migrations.AddField(
            model_name='address',
            name='persons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contact_box.Person'),
        ),
    ]
