# Generated by Django 2.1.1 on 2018-10-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_box', '0002_auto_20181011_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='flat_number',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
