# Generated by Django 2.1.1 on 2018-10-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_box', '0003_auto_20181011_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_address',
            field=models.EmailField(max_length=70),
        ),
    ]
