# Generated by Django 2.1.1 on 2018-11-15 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_box', '0005_auto_20181113_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='addresses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact_box.Address'),
        ),
    ]
